images:
- image: simple-app
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: simple-app
  path: test/e2e/assets/simple-app
  pack:
    build:
      builder: cloudfoundry/cnb:bionic
