apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbld-simple-app-build-local-pack
spec:
  selector:
    matchLabels:
      app: kbld-simple-app-build-local-pack
  template:
    metadata:
      labels:
        app: kbld-simple-app-build-local-pack
    spec:
      containers:
      - name: my-app
        image: simple-app
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: simple-app
  path: test/e2e/assets/simple-app
  pack:
    build:
      builder: cloudfoundry/cnb:bionic
