name: test-gh
on: [push]
jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: src/github.com/k14s/kbld
    - name: Run Tests
      run: |
        set -e -x
        export GOPATH=$(echo `pwd`/../../../../)
        # install ytt for build
        mkdir -p tmp/bin/
        wget -O- https://k14s.io/install.sh | K14SIO_INSTALL_BIN_DIR=tmp/bin bash
        rm -f tmp/bin/kbld
        export PATH=`pwd`/tmp/bin:$PATH
        git config --global user.email "dummy@k14s.io"
        git config --global user.name "Dummy dummy"
        ./hack/build.sh
        ./hack/test.sh
        ./hack/build-binaries.sh
        # TODO no e2e since there is no docker creds env
